version: "3"

//Note that the service isn't reachable from the outside, you need to expose it with 
// tools like nginx or traefik. Nginx-Proxy-Manager is what we use.

x-common-volumes: &common-volumes
  volumes:
    - static-volume:/home/website/statics
    - media-volume:/home/website/media

services:
  db:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - db-data:/var/lib/postgresql/data

  web:
    image: unitystation/central-command:latest
    environment:
      - DEBUG=0
    env_file: ./.env
    expose:
      - 8000
    command: gunicorn central-command.wsgi:application --bind 0.0.0.0:8000
    <<: *common-volumes

volumes:
  db-data:
  static-volume:
  media-volume:
